- README.md
- app/initializers/raven-setup.js
We disable sentry in the development environments
> Add bool to config so that you can disable sentry

- README.md
> Use gender neutral language in README

- app/instance-initializers/raven-setup.js
> Emit warning on exception during sentry initialization

- README.md
- app/instance-initializers/raven-setup.js
raven.js allows for ignoreErrors, transport to be set with its configuration. We had a need to utilize some of these.
> Allow passing of arbitrary options to raven.js

- blueprints/ember-cli-sentry/index.js
- index.js
> Install and import raven-js dependency

- index.js
Fixes https://github.com/damiencaselli/ember-cli-sentry/issues/37
> Import the non-minified version of raven-js

- README.md
- blueprints/ember-cli-sentry/index.js
I didn't notice any incompatibility so far, but I didn't run any extensive testing.
> Updates to raven.js 3.3

- addon/services/raven.js
When the rejected promise is not an Error, Sentry always received `Unhandled Promise error detected` (or whatever it has been updated to in the app).
This PR tries to provide a bit more informative message so that when in Sentry, everything does not show up as quoted above.
Note: Using `Ember.typeOf` is Ember 1.13+ compatible.
> Better message for rejected promises

- addon/services/raven.js
- app/instance-initializers/raven-setup.js
> Move setup code into the service and add "ignoreUrls" support

- README.md
- addon/services/raven.js
- app/initializers/raven.js
- app/instance-initializers/raven-setup.js
- app/services/raven.js
- tests/dummy/app/services/raven.js
Resolves https://github.com/damiencaselli/ember-cli-sentry/issues/82
> Replace "serviceName" property with fixed "raven" service

- CHANGELOG.md
- package.json
- yarn.lock
... because we're lazy and it sucks to have to update the file by hand.
Note that the changelog generator will only include PRs that are labels correctly.
> Generate CHANGELOG using `lerna-changelog`

- .travis.yml
- testem.js
addresses https://github.com/damiencaselli/ember-cli-sentry/pull/110#issuecomment-359361581
> testem: Use headless Chrome to run tests

- .travis.yml
> CI: Use Node.js 4.x

- README.md
- tests/dummy/config/environment.js
v3.0 has no `cdn` option anymore...
> Remove `cdn.ravenjs.com` from CSP suggestion

- index.js
- package.json
- tests/unit/import-test.js
- yarn.lock
Resolves https://github.com/damiencaselli/ember-cli-sentry/issues/112
> Remove `ember-cli-node-assets` dependency

- addon/index.js
- addon/services/raven.js
- app/instance-initializers/raven-setup.js
- tests/dummy/app/app.js
- tests/dummy/app/components/x-button.js
- tests/dummy/app/controllers/application.js
- tests/dummy/app/router.js
- tests/dummy/app/routes/application.js
- tests/helpers/destroy-app.js
- tests/helpers/module-for-acceptance.js
- tests/helpers/start-app.js
> Use "RFC 176 Imports"

- .travis.yml
see https://github.com/Turbo87/auto-dist-tag/pull/24
> CI: Adjust `skip_cleanup` behavior to fix `auto-dist-tag`

- package.json
- yarn.lock
> Update `lerna-changelog` to v0.8.0

- package.json
- yarn.lock
see https://github.com/broccolijs/broccoli-merge-trees/blob/master/CHANGELOG.md#300
> Update `broccoli-merge-trees` to v3.0.1

- package.json
- yarn.lock
This does not seem to be used anywhere
> Remove unused `ember-cli-app-version` dev dependency
