- README.md
- index.js
We have an "offline" packaged app with status-checking of offline-mode, loading resources from CDN breaks. Therefore we load Raven separately in Bower.
Might be useful for others!
> Add option to skip CDN loading

- app/initializers/raven-setup.js
Per the RSVP.js documentation (https://github.com/tildeio/rsvp.js#error-handling), RSVP.onerror has been depreciated in favor of RSVP.on.  Additionally, this pull request ignores false positives by ignoring callbacks with an undefined error.
> Update depreciated RSVP.onerror to RSVP.on 

- app/initializers/raven-setup.js
- index.js
The implementation is roughly similar, but it makes sense to me to use the
shared version of the Ember plugin (this way all ember-cli-sentry users
benefit from fixes upstream).
Current plugin link:
https://github.com/getsentry/raven-js/blob/d3e70256b6d1dfcfd20ddae89d0d7acd3403b579/plugins/ember.js
> Use the Ember plugin for Raven.

- app/initializers/raven.js
Fix 
```
DEPRECATION: The `initialize` method for Application initializer 'raven' should take only one argument - `App`, an instance of an `Application`. [deprecation id: ember-application.app-initializer-initialize-arguments] See http://emberjs.com/deprecations/v2.x/#toc_initializer-arity for more details.
```
> Initializer fixup for Ember 2.1

- app/instance-initializers/raven-setup.js
Hey Damien,
this is basically the only change I need in order to make `ember-cli-deploy-sentry` work really nice with your addon.
If you don't like the coupling to the DOM in the instance-initializer, we could possibly also read this from the logger service and I would implement it there.
Just let me know, what you prefer...
Best regards, 
Domme
> Allow specifying sentry release on the service

- app/instance-initializers/raven-setup.js
Hit a compatibility problems with Object.assign (most notable in some PhantomJS runs, and would see in pre-Edge IE).
> Using Ember.merge to avoid compatibility issues.

- app/instance-initializers/raven-setup.js
Ember.merge is deprecated in the current beta release, generating a warning when using this plugin.
See: https://github.com/emberjs/ember.js/pull/12303
This PR switches to using `Ember.assign` if available.
I used the same backwards compatible strategy that `ember-power-select` is using. See: https://github.com/cibernox/ember-power-select/pull/406
All tests pass for me locally.
> switch to Ember.assign (Ember.merge deprecated)

- app/instance-initializers/raven-setup.js
That logger line was annoying some folks here, so would be nice to only emit it when debugging is enabled.
> Stay quiet unless debugging enabled.

- addon/utils/parse-regex-errors.js
- app/instance-initializers/raven-setup.js
- tests/unit/utils/parse-regex-errors-test.js
For the issue #49, it looks like the ember-cli team won't support this.
See https://github.com/ember-cli/ember-cli/issues/5954#issuecomment-223831128.
Do you mind considering this improvement?
> Parse RegExp in ignoreErrors

- addon/services/raven.js
Uses RSVP labels as the context of errors.
https://guides.emberjs.com/v2.10.0/ember-inspector/promises/#toc_labeling-promises
> Support RSVP labels

- index.js
This change respects the `--silent` flag when building. I've confirmed this works locally. 
> Every addon is sent an instance of the parent application’s command line output stream. If you want to write out to the command line in your addon’s index.js file, you should use this.ui.writeLine rather than console.log. This will make the output obey the --silent flag available with many ember-cli commands.
from https://ember-cli.com/extending/#writing-to-the-command-line
> In index.js, use ui.writeLine instead of console.log to respect --silent

- .travis.yml
Example release instructions from now on:
```
npm version minor
git push origin master --follow-tags
```
> CI: Publish tags automatically to npm

- addon/services/raven.js
- package.json
While this does NOT fix the sentry running in FastBoot issue, is does stop raven from causing the Fastboot server to crash whenever an error takes place.
raven-js depends on XMLHTTPRequest to send reports to Sentry, unfortunatley, in fastboot that's not available and the result is a irrecoverable crash for the server.  There's an official patch upstream in raven-js for this, but they seem pretty slow to release versions so this handles it in the meantime.
Ideally, we'll get back to looking at versions that support both raven-node and raven-js for true fastboot support 👍 
See also https://github.com/damiencaselli/ember-cli-sentry/issues/77
> Check for Fastboot in isRavenUsable

- addon/services/raven.js
- tests/dummy/app/controllers/application.js
This exposes raven's `captureBreadcrumb` method via the `raven` service.
> add RavenService#captureBreadcrumb

- index.js
- package.json
- yarn.lock
This PR fixes nested addon import behavior. Starting from ember-cli 2.7, there is `this.import` that does the correct root app detection, so we can check if it exists, before 2.7 there is a polyfill, which is `findHost` in this PR.
This is the way, how nesting fails:
```
App <-- at this level, include of the addon wasn't happening
-- Included addon
-- has dependency on ember-cli-sentry
```
I've kinda backported changes from ember-cli-node-assets:
https://github.com/dfreeman/ember-cli-node-assets/blob/master/index.js
> Update ember-cli-node-assets and use correct .import

- package.json
This reverts commit ed0360a2aff6399b2fa791b211777f2a1c1740bc.
These dependencies aren't actually being used anywhere.
> Revert "Add jsdoc dependencies for doc generation"

- README.md
Upgrade instructions should instead be included in https://github.com/damiencaselli/ember-cli-sentry/blob/master/CHANGELOG.md
Resolves https://github.com/damiencaselli/ember-cli-sentry/issues/101
> README: Remove broken link

- package.json
- yarn.lock
This enables RFC 176 style module imports.
> Upgrade `ember-cli-babel` to ^6.6.0

- .eslintrc.js
- addon/index.js
- addon/services/raven.js
The use of Ember.Logger was added to deprecations in ember 3.2. This
commit replaces any Ember.Logger calls with console.
ESlint rules were updated to avoid tests to fail.
This should fix #134.
Thsi PR contains changes that were requested in https://github.com/damiencaselli/ember-cli-sentry/pull/135#discussion_r216935884 by @Turbo87.
> Use console rather than Ember.Logger

- .travis.yml
- package.json
Travis tests are currently running on node v4.
However, some dependencies require `node >=6`, resulting in travis tests failing.
To solve this, I bumped travis node version to 6 and updated `package.json` accordingly. I doubt there are many node 4 users around any more.
> Drop node v4 support

- addon/services/raven.js
Currently when `captureException` or `captureMessage` on the raven service are used while Raven is not configured (development and test), it throws the exception or message.
This is not the behavior of [ravenjs](https://docs.sentry.io/clients/javascript/usage/) when it has not been configured and certainly doesn't seem like correct behavior for this package. It makes it impossible to write tests around behavior that reports messages or exceptions to Sentry.
> Do not throw error/message when raven disabled

- package.json
- yarn.lock
This updates us to the latest release before Sentry introduced their new JavaScript SDK.
> Update `raven-js` to v3.27.0

- package.json
- yarn.lock
because we don't actually use it at all...
> Remove unused `ember-cli-release` dev dependency

- README.md
- package.json
- yarn.lock
This PR implicitly drops support for Ember CLI versions below 2.13 due to https://github.com/babel/ember-cli-babel/tree/v7.1.2#compatibility
> Update `ember-cli-babel` to v7.1.2

- vendor/raven-shim.js
Ember's AMD loader is tolerant if you don't do this, but other build systems are not. I'm experimenting with getting a large number of addons compatible with other build tools (like Webpack and Parcel). In my testing this bug came up.
The bug is that consumers can't tell whether it's already a module that has a default export vs some random object that needs to get wrapped in another `{ default: ... }` to make it compatibility with consuming modules.
> Mark raven-shim as an ES module

- README.md
https://github.com/damiencaselli/ember-cli-sentry/commit/0bd3e842ac1c0505c06acca9f5ba876e2f6c79b1 added the ability to pass the `environment` to Raven.js as per https://docs.sentry.io/clients/javascript/config/ but this option doesn't seem to have a default or to be documented in the README
An alternative/addition would be to default it to the current ember-cli environment
> Add documentation around environment passing

- addon/services/raven.js
To fix this deprecation: https://deprecations.emberjs.com/v3.x/#toc_computed-property-volatile
> Use native getter instead of volatile cp
